name: Vue env - Quick Start - Ripple - Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: bitsrc/nightly:latest
    env:
      HOME: /home/bituser
        
    steps:
    - name: Initialize a workspace
      run: |
        bvm config set RELEASE_TYPE nightly
        bvm config
        bvm versions
        bvm upgrade
        bit --version
        bit init my-vue-workspace --bare --log error
    - name: Initialize a bit sign directory
      run: |
        mkdir ~/bit-sign
        cd ~/bit-sign
        bit init
        bit config set user.token ${{ secrets.BIT_USER_TOKEN }}
        bit install @teambit/dot-cli.sign
        CURRENT_DIR=$(pwd)
        echo "Current path is: $CURRENT_DIR"
        echo "{ \"file://$CURRENT_DIR/node_modules/@teambit/dot-cli.sign\": {} }" > ~/.bitrc.jsonc
        cat ~/.bitrc.jsonc
    - name: Bit sign get-hello-world
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.hello-world/get-hello-world --multiple --rebuild --log error
    - name: Bit sign ui/hello-world
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.hello-world/ui/hello-world --multiple --rebuild --log error
    - name: Bit sign hello-world-app
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.hello-world/hello-world-app --multiple --rebuild --log error
    - name: Bit sign todomvc-todo-entity
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.todomvc/todo-entity --multiple --rebuild --log error
    - name: Bit sign todomvc-todo
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.todomvc/todo --multiple --rebuild --log error
    - name: Bit sign todomvc-todo-list
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.todomvc/todo-list --multiple --rebuild --log error
    - name: Bit sign todomvc-todo-store
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.todomvc/todo-store --multiple --rebuild --log error
    - name: Bit sign todomvc-header
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.todomvc/header --multiple --rebuild --log error
    - name: Bit sign todomvc-footer
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.todomvc/footer --multiple --rebuild --log error
    - name: Bit sign todomvc-toggle-all
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.todomvc/toggle-all --multiple --rebuild --log error
    - name: Bit sign todomvc-app
      run: |
        cd my-vue-workspace
        bit sign learnbit-vue.todomvc/app --multiple --rebuild --log error
    continue-on-error: false
