name: Vue env - Learnbit - Apps - Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: bitsrc/nightly:latest
    env:
      HOME: /home/bituser
        
    steps:
    - name: Initialize a workspace
      run: |
        bvm config set RELEASE_TYPE nightly
        bvm config
        bvm versions
        bvm upgrade
        bit --version
        bit new vue my-vue-workspace --env bitdev.vue/vue-env
    - name: Check initial status
      run: |
        cd my-vue-workspace
        bit list
        bit status
        bit templates
    - name: Import apps
      run: |
        cd my-vue-workspace
        # import
        bit import learnbit-vue.basic/my-vite-app
        bit import learnbit-vue.basic/my-vite-hello-app
        bit import learnbit-vue.basic/my-vite-ssr-app
        bit import learnbit-vue.design-system/apps/global-theme
        bit import learnbit-vue.design-system/apps/nested-themes
        bit import learnbit-vue.data-fetching/brewery-app
        bit import learnbit-vue.graphql/servers/my-apollo-server
        bit import learnbit-vue.graphql/user-app
        # bit install
        # check
        bit list
        cat workspace.jsonc
        bit app list
        bit status
    - name: my-vite-app
      run: |
        cd my-vue-workspace
        bit run my-vite-app &
        checkserver http://localhost:3000
        pkill -f "bit run my-vite-app"
    - name: my-vite-hello-app
      run: |
        cd my-vue-workspace
        bit run my-vite-hello-app &
        checkserver http://localhost:3000
        pkill -f "bit run my-vite-hello-app"
    - name: my-vite-ssr-app
      run: |
        cd my-vue-workspace
        bit run my-vite-ssr-app &
        checkserver http://localhost:3000
        pkill -f "bit run my-vite-ssr-app"
    - name: global-theme
      run: |
        cd my-vue-workspace
        bit run global-theme &
        checkserver http://localhost:3000
        pkill -f "bit run global-theme"
    - name: nested-themes
      run: |
        cd my-vue-workspace
        bit run nested-themes &
        checkserver http://localhost:3000
        pkill -f "bit run nested-themes"
    - name: brewery-app
      run: |
        cd my-vue-workspace
        bit run brewery-app &
        checkserver http://localhost:3000
        pkill -f "bit run brewery-app"
    - name: user-app
      run: |
        cd my-vue-workspace
        bit run my-apollo-server --port 4000 &
        checkserver http://localhost:4000
        bit run user-app &
        checkserver http://localhost:3000
        pkill -f "bit run user-app"
        pkill -f "bit run my-apollo-server"
    - name: Lint and test
      run: |
        cd my-vue-workspace
        bit list
        bit status
        bit lint
        bit test
    - name: Create a local scope, compile and export
      run: |
        barescope my-org.my-scope-name my-vue-workspace
        cd my-vue-workspace
        bit scope rename org.scope-name my-org.my-scope-name --refactor
        bit link
        bit compile
        bit tag --message "initial tag"
        bit export
    continue-on-error: false
